### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by vladiftimie** [louk-lang/louk#126]
Hey! Are you still working on this project? I think this notation, paired with Stylus, makes the code much easier to read. If you're still on it, I could maybe help out. :-)
So far I've tried it out on my own and it more or less works, but it's obvious this is in the early stages of development.

**Comment by agorischek** [comment]
Hi there, glad you like the syntax! I upgrade dependencies from time to time but haven't actively been developing the feature set. My recent projects haven't been Vue-based so just haven't had the reason to. The main things I was starting to look at when I was last investing were making Louk work with ESLint and Prettier. It would also ideally be included as a vue-cli extension to be fully part of proper Vue workflows. There are also a number of things worth doing in the library itself, which still have open issues tracking them. If you're interesting in contributing, I'd be happy to have your help!
